import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import type { DecisionSpec } from "./types.js";

const safeIdentifier = (name: string): string => {
  const parts = name.split(/[^a-zA-Z0-9]+/).filter(Boolean);
  const camel = parts.map((p, i) => i === 0 ? p.toLowerCase() : p[0]!.toUpperCase() + p.slice(1)).join("");
  return /^\d/.test(camel) ? `decision${camel}` : camel || "decision";
};

function serialize(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

export function generateMigration(decisionName: string, spec: DecisionSpec, model?: string): string {
  const fn = safeIdentifier(decisionName);
  const question = spec.type === "choice"
    ? `choice(${serialize(spec.instructions)}, ${serialize(spec.criteria)})`
    : spec.type === "noul"
      ? `noul(${serialize(spec.instructions)}, ${serialize(spec.criteria ?? null)})`
      : `score(${serialize(spec.instructions)}, ${serialize(spec.criteria)})`;
  const imports = spec.type === "choice" ? "choice, TypeSafeClient" : spec.type === "noul" ? "noul, TypeSafeClient" : "score, TypeSafeClient";
  const resolvedModel = spec.model ?? model;

  return `import { ${imports} } from "@typesafe-ai/sdk";\n\n` +
    `const client = new TypeSafeClient(${resolvedModel ? `{ defaultModel: ${JSON.stringify(resolvedModel)} }` : ""});\n\n` +
    `/** Generated by JevSwitch. Review before wiring it into production. */\n` +
    `export async function ${fn}(state: unknown) {\n` +
    `  const response = await client.systemOne({\n` +
    `    state: state as never,\n` +
    `    questions: {\n` +
    `      decision: ${question},\n` +
    `    },\n` +
    `  });\n\n` +
    `  return response.answers.decision;\n` +
    `}\n`;
}

export async function writeMigration(decisionName: string, spec: DecisionSpec, output: string, model?: string): Promise<string> {
  const path = resolve(output);
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, generateMigration(decisionName, spec, model), "utf8");
  return path;
}
